#!/usr/bin/env python

'''
配置项管理工具(dotfiles manager)，配置项指保存配置信息的文件或包含配置文件的文件夹，配置文件尽量保证是文本文件

Usage:
    dfm add <path>

Commands:
    add 添加一个配置项，并将其移动至配置项目录并创建相应软链接

Arguments:
    path 配置项路径

Options:
    -h --help
'''

from docopt import docopt
from pathlib import Path
import yaml
import os
import platform
import shutil


dotfiles_root = os.path.join(*[Path.home(), "dotfiles"])


def __load_config():
    config_path = os.path.join(*[dotfiles_root, "dfm.yaml"])
    if not os.path.isfile(config_path):
        return {}
    with open(config_path) as fin:
        config = yaml.load(fin, Loader=yaml.SafeLoader)
        return config


def __save_config(config):
    config_path = os.path.join(*[Path.home(), "dotfiles", "dfm.yaml"])
    with open(config_path, 'w') as fout:
        fout.write(yaml.dump(config, Dumper=yaml.SafeDumper))


def __get_keep_path(path):
    relpath = os.path.relpath(path, Path.home())
    keep_path = os.path.join(
        *[dotfiles_root, platform.system().lower(), relpath])
    return keep_path


def __add(path, config):
    abspath = os.path.abspath(path)
    keep_path = __get_keep_path(abspath)
    os.makedirs(os.path.dirname(keep_path), exist_ok=True)
    shutil.move(abspath, keep_path)
    os.symlink(keep_path, abspath)

    df_path = os.path.relpath(keep_path, dotfiles_root)
    home_path = os.path.relpath(abspath, Path.home())
    if "dotfiles" not in config:
        config["dotfiles"] = {}
    if df_path not in config["dotfiles"]:
        config["dotfiles"][df_path] = {}
    system = platform.system().lower()
    if system not in config["dotfiles"][df_path]:
        config["dotfiles"][df_path][system] = {}
    config["dotfiles"][df_path][platform.system().lower()]["path"] = home_path
    return config


def __use(args, config):
    return config


def __dispatch(args):
    def check_add_args():
        path = os.path.abspath(args["<path>"])
        if not os.path.isfile(path) and not os.path.isdir(path):
            print("%s is not valid file or directory" % path)
            exit(-1)
        if path.startswith(dotfiles_root):
            print("%s cannot be in dotfiles" % path)
            exit(-1)
        if not path.startswith(str(Path.home())):
            print("%s must be in home" % path)
            exit(-1)
        if os.path.exists(__get_keep_path(path)):
            print("%s has been kept in dotfiles" % path)
            exit(-1)

    if args["add"]:
        check_add_args()

        def add(config):
            return __add(args["<path>"], config)
        return add
    elif args["use"]:
        return __use
    else:
        return None


def main():
    args = docopt(__doc__)
    print(args)

    config = __load_config()
    print(config)

    config = __dispatch(args)(config)
    __save_config(config)


if __name__ == "__main__":
    main()
